bug: 30014
- removed the typo, which is not useful or related at all to the cause of DOMAIN_NOT_EMPTY exeption anyway.

- include a few entry DNs in the error msg for the DOMAIN_NOT_EMPTY exception.
e.g.  the error nessage now looks like:
zmprov dd test.com
ERROR: account.DOMAIN_NOT_EMPTY (domain not empty: test.com (remaining entries: [uid=user1,ou=people,dc=test,dc=com] [uid=user2,ou=people,dc=test,dc=com] ...))

http://bugzilla.zimbra.com/show_bug.cgi?id=30014

Copied from Perforce
 Change: 140327